name: Build and Publish 1.21.1

on:
  push:
    branches: [ "**" ]
    tags: [ "v*" ]

permissions:
  contents: write

jobs:
  build-and-package:
    name: Build and Publish
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build project
        run: .\gradlew.bat build --stacktrace

      - name: Upload Mod artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AcceleratedRecoiling-${{ github.ref_name }}-build-${{ github.run_number }}
          path: build/libs/*.jar
          if-no-files-found: warn

      - name: Publish to GitHub Releases
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
          generate_release_notes: true

      - name: Publish to CurseForge & Modrinth
        if: startsWith(github.ref, 'refs/tags/v')
        uses: kir-antipov/mc-publish@v3.3
        with:
          files: build/libs/!(*-dev|-sources|-javadoc).jar

          name: ${{ github.ref_name }}
          version: ${{ github.ref_name }}

          loaders: fabric

          game-versions: 1.21.1

          curseforge-id: ${{ secrets.CF_PROJECT_ID }}
          curseforge-token: ${{ secrets.CF_TOKEN }}
          modrinth-id: ${{ secrets.MODRINTH_PROJECT_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          version-type: release